function pccs_change(v){
	var pccs=new province_city_county_select();
	var str="0";
	for(i=0;i<v;i++){
		str+=("_"+(document.getElementById(pccs.s[i]).selectedIndex-1));
	};
	var ss=document.getElementById(pccs.s[v]);
	with(ss){
		length = 0;
		options[0]=new Option(pccs.defaultValue[v],pccs.defaultValue[v]);
		if(v && document.getElementById(pccs.s[v-1]).selectedIndex>0 || !v){
			if(typeof(pccs.Items[str]) != "undefined"){
				ar = pccs.Items[str];
				for(i=0;i<ar.length;i++){
					options[length]=new Option(ar[i],ar[i]);
				}
				if(v){
					options[0].selected = true; 
				}
			}
		}
		if(++v<pccs.s.length){
			pccs_change(v);
		}
	}
}

function province_city_county_select(){}

province_city_county_select.prototype={
	s:["s_province","s_city","s_county"],
	defaultValue:["Province","Region","County"],
	Items:{},
	add:function(id,iArray){
		this.Items[id] = iArray;
	},
	init:function(){  //初始化函数
		this.add("0_0_0", ["Anqing", "Huaining", "Qianshan", "Susong", "Taihu", "Tongcheng", "Wangjiang", "Yuexi", "Zongyang"]);
		this.add("0_0_1", ["Bengbu", "Guzhen", "Huaiyuan", "Wuhe"]);
		this.add("0_0_2", ["Boxian", "Guoyang", "Lixin", "Mengcheng"]);
		this.add("0_0_3", ["Chao", "Hanshan", "He", "Lujiang", "Wuwei"]);
		this.add("0_0_4", ["Dongzhi", "Guichi", "Qingyang", "Shitai"]);
		this.add("0_0_5", ["Chuxian", "Dingyuan", "Fengyang", "Jiashan", "Lai'an", "Quanjiao", "Tianchang"]);
		this.add("0_0_6", ["Funan", "Fuyang", "Jieshou", "Linquan", "Taihe", "Yaohai"]);
		this.add("0_0_7", ["Changfeng", "Feidong", "Feixi", "Hefei"]);
		this.add("0_0_8", ["Huaibei", "Suixi"]);
		this.add("0_0_9", ["Fengtai", "Huainan"]);
		this.add("0_0_10", ["Qimen", "She", "Taiping", "Tunxi", "Xiuning", "Yi"]);
		this.add("0_0_11", ["Huoqiu", "Huoshan", "Jinzhai", "Lu An", "Shou", "Shucheng"]);
		this.add("0_0_12", ["Dangtu", "Maanshan"]);
		this.add("0_0_13", ["Changshu", "Dangshan", "Kunshan", "Lingbi", "Shazhou", "Si", "Suzhou", "Taicang", "Wujiang", "Wuxian", "Xiao", "Yongqiao"]);
		this.add("0_0_14", ["Tongling"]);
		this.add("0_0_15", ["Fanchang", "Nanling", "Wuhu"]);
		this.add("0_0_16", ["Guangde", "Jing", "Jingde", "Jixi", "Langxi", "Ningguo", "Xuanzhou"]);
		this.add("0_1_0", ["Beijing", "Changping", "Daxing", "Fangshan", "Huairou", "Mentougou", "Miyun", "Pinggu", "Shunyi", "Tongzhou", "Yanqing"]);
		this.add("0_2_0", ["Ba", "Bishan", "Changshou", "Chengkou", "Chongqing", "Dazu", "Dianjiang", "Fengdu", "Fengjie", "Fuling", "Hechuan", "Jiangbei", "Jiangjin", "Kai", "Liangping", "Nanchuan", "Pengshui", "Qianjiang", "Qijiang", "Rongchang", "Shizhu", "Tongliang", "Tongnan", "Wan", "Wulong", "Wushan", "Wuxi", "Xiushan", "Yongchuan", "Youyang", "Yunyang", "Zhong"]);
		this.add("0_3_0", ["Changle", "Chongren", "Dongxiang", "Fuqing", "Fuzhou", "Guangchang", "Jinxi", "Le'an", "Lianjiang", "Lichuan", "Linchuan", "Luoyuan", "Minhou", "Minqing", "Nancheng", "Nanfeng", "Yihuang", "Yongtai", "Zixi"]);
		this.add("0_3_1", ["Changting", "Liancheng", "Luojiang", "Shanghang", "Wuping", "Yongding", "Zhangping"]);
		this.add("0_3_2", ["Chongan", "Guangze", "Jian'ou", "Jianyang", "Nanping", "Pucheng", "Shaowu", "Shunchang", "Songxi", "Zhenghe"]);
		this.add("0_3_3", ["Fu'an", "Fuding", "Gutian", "Jiaocheng", "Pingnan", "Shouning", "Xiapu", "Zherong", "Zhouning"]);
		this.add("0_3_4", ["Putian", "Putian County", "Xianyou"]);
		this.add("0_3_5", ["Anxi", "Dehua", "Hui'an", "Jinjiang", "Jinmen", "Nan'an", "Sanyuan", "Shishi", "Yongchun"]);
		this.add("0_3_6", ["Datian", "Jiangle", "Jianning", "Mingxi", "Ninghua", "Qingliu", "Sha", "Shanming", "Taining", "Yong'an", "Youxi"]);
		this.add("0_3_7", ["Tong'an", "Xiamen"]);
		this.add("0_3_8", ["Changtai", "Dongshan", "Hua'an", "Longhai", "Nanjing", "Pinghe", "Zhangpu", "Zhangzhou", "Zhao'an"]);
		this.add("0_4_0", ["Baiyin", "Huining", "Jingtai", "Jingyuan", "Pingchuan"]);
		this.add("0_4_1", ["Dingxi", "Lintao", "Longxi", "Min", "Tongwei", "Weiyuan", "Zhang"]);
		this.add("0_4_2", ["Jon\u00e9\u201d", "Lintan", "Luqu", "Maqu", "T\u00e9\u201d\u0161wo", "Xiahe", "Zhugqu"]);
		this.add("0_4_3", ["Jiayuguan"]);
		this.add("0_4_4", ["Jinchuan", "Yongchang"]);
		this.add("0_4_5", ["Aksai Kazakh", "Anxi", "Dunhuang", "Jinta", "Subei Mongol", "Suzhou", "Yumen"]);
		this.add("0_4_6", ["Gaolan", "Liangzhou", "Yongdeng", "Yuzhong"]);
		this.add("0_4_7", ["Dongxiang", "Guanghe", "Hezheng", "Jishishan Bonan, Dongxiang and Salar", "Kangle", "Linxia", "Linxia Shi", "Yongjing"]);
		this.add("0_4_8", ["Cheng", "Dangchang", "Hui", "Kang", "Li", "Liangdang", "Wen", "Wudu", "Xihe"]);
		this.add("0_4_9", ["Chongxin", "Huating", "Jingchuan", "Jingning", "Lingtai", "Pingliang", "Zhuanglang"]);
		this.add("0_4_10", ["Hezheng", "Huachi", "Huan", "Ning", "Qingyang", "Xifeng", "Zhengning", "Zhenyuan"]);
		this.add("0_4_11", ["Gangu", "Qin'an", "Qingcheng", "Tianshui", "Wushan", "Zhangjiachuan Hui"]);
		this.add("0_4_12", ["Heshui", "Minqin", "Tianzhu Tibetan", "Wuwei"]);
		this.add("0_4_13", ["Gaotai", "Linze", "Minle", "Shandan", "Sunan Yugur", "Zhangye"]);
		this.add("0_5_0", ["Chaonan", "Chaozhou", "Raoping"]);
		this.add("0_5_1", ["Dongyuan"]);
		this.add("0_5_2", ["Futian", "Gaoming", "Nanhai", "Sanshui", "Shunde"]);
		this.add("0_5_3", ["Conghua", "Guangzhou", "Huaxian", "Nansha", "Panyu", "Zengcheng"]);
		this.add("0_5_4", ["Dongyuan", "Heping", "Lianping", "Lungchuan", "Yuancheng", "Zijin"]);
		this.add("0_5_5", ["Boluo", "Huidong", "Huiyang", "Huizhou", "Longmen"]);
		this.add("0_5_6", ["Enping", "Heshan", "Jiangmen", "Kaiping", "Taishan", "Xinhui"]);
		this.add("0_5_7", ["Huilai", "Jiedong", "Jiexi", "Puning", "Rongcheng"]);
		this.add("0_5_8", ["Dianbai", "Gaozhou", "Huazhou", "Maoming", "Xinyi"]);
		this.add("0_5_9", ["Dapu", "Fengshun", "Jiaoling", "Mei", "Meizhou", "Pingyuan", "Wuhua", "Xingning"]);
		this.add("0_5_10", ["Fogang", "Liannan Yao", "Lianshan Zhuang and Yao", "Lianzhou", "Qingcheng", "Qingxin", "Yangshan", "Yingde"]);
		this.add("0_5_11", ["Chaoyang", "Chenghai", "Shantou"]);
		this.add("0_5_12", ["Haifeng", "Lufeng", "Luhe", "Shanwei"]);
		this.add("0_5_13", ["Lechang", "Nanxiong", "Qujiang", "Renhua", "Ruyuan Yao", "Shaoguan", "Shixing", "Wengyuan", "Xinfeng"]);
		this.add("0_5_14", ["Bao'an", "Shenzhen"]);
		this.add("0_5_15", ["Yangchun", "Yangdong", "Yangjiang", "Yangxi"]);
		this.add("0_5_16", ["Luoding", "Xinxing", "Yun'an", "Yunan", "Yuncheng"]);
		this.add("0_5_17", ["Leizhou", "Lianjiang", "Suixi", "Wuchuan", "Xuwen", "Zhenjiang"]);
		this.add("0_5_18", ["Deqing", "Fengkai", "Gaoyao", "Guangning", "Huaiji", "Sihui", "Zhaoqing"]);
		this.add("0_5_19", ["Zhongshan"]);
		this.add("0_5_20", ["Doumen", "Zhuhai"]);
		this.add("0_6_0", ["Baise", "Debao", "Jingxi", "Leye", "Lingyun", "Longlin Various Nationalities", "Napo", "Pingguo", "Tiandong", "Tianlin", "Tianyang", "Xilin"]);
		this.add("0_6_1", ["Beihai", "Hepu"]);
		this.add("0_6_2", ["Changzhou", "Daxin", "Fusui", "Longzhou", "Ningming", "Pingxiang", "Tiandeng"]);
		this.add("0_6_3", ["Fangcheng", "Shangsi"]);
		this.add("0_6_4", ["Gui", "Guiping", "Pingnan"]);
		this.add("0_6_5", ["Gongcheng Yao", "Guanyang", "Guilin", "Lingchuan", "Lingui", "Lipu", "Longsheng Various Nationalities", "Pingle", "Quanzhou", "Xing\u00e9\u02c6\u00a5\u00e6\u00aa\u0192n", "Yangshuo", "Yongfu", "Ziyuan"]);
		this.add("0_6_6", ["Bama Yao", "Dahua Yao \t", "Donglan", "Du\u00e9\u02c6\u00a5\u00e6\u00aa\u0192n Yao", "Fengshan", "Hechi", "Huanjiang Maonan", "Luocheng Mulao", "Nandan", "Tian'e", "Yanshan"]);
		this.add("0_6_7", ["Fuchuan Yao", "He", "Zhaoping", "Zhongshan"]);
		this.add("0_6_8", ["Heshan", "Jinxiu Yao", "Laibin", "Wuxuan", "Xiangzhou", "Xincheng"]);
		this.add("0_6_9", ["Liucheng", "Liujiang", "Liuzhou", "Luzhai", "Rong'an", "Rongshui Miao", "Sanjiang Dong"]);
		this.add("0_6_10", ["Binyang", "Heng", "Long'an", "Mashan", "Nanning", "Shanglin", "Wuming", "Yongning"]);
		this.add("0_6_11", ["Lingshan", "Pubei", "Qinzhou"]);
		this.add("0_6_12", ["Cangwu", "Cenxi", "Mengshan", "Teng", "Wuzhou"]);
		this.add("0_6_13", ["Beiliu", "Bobai", "Dingbian", "Fugu", "Hengshan", "Jia", "Jingbian", "Luchuan", "Mizhi", "Qingjian", "Rong", "Shenmu", "Suide", "Wubu", "Yufeng", "Yulin", "Zizhou"]);
		this.add("0_7_0", ["Anshun", "Guanling Buyei and Miao", "Pingba", "Puding", "Zhenning Buyei and Miao", "Ziyun Miao and Buyei"]);
		this.add("0_7_1", ["Bijie", "Dafang", "Hezhang", "Jinsha", "Nayong", "Qianxi", "Weining Yi, Hui and Miao", "Zhijin"]);
		this.add("0_7_2", ["Guiyang", "Kaiyang", "Qingzhen", "Xifeng", "Xiuwen"]);
		this.add("0_7_3", ["Liuzhi", "Pan", "Shuicheng", "Zhongshan"]);
		this.add("0_7_4", ["Cengong", "Congjiang", "Danzhai", "Huangping", "Jianhe", "Jinping", "Kaili", "Leishan", "Liping", "Majiang", "Rongjiang", "Sansui", "Shibing", "Taijiang", "Tianzhu", "Zhenyuan"]);
		this.add("0_7_5", ["Changshun", "Dushan", "Duyun", "Fuquan", "Guiding", "Huaxi", "Libo", "Longli", "Luodian", "Pingtang", "Sandu Shui", "Weng'an"]);
		this.add("0_7_6", ["Anlong", "Ceheng", "Pu'an", "Qinglong", "Wangmo", "Xingren", "Xingyi", "Zhenfeng"]);
		this.add("0_7_7", ["Dejiang", "Jiangkou", "Shiqian", "Sinan", "Songtao Miao", "Tongren", "Wanshan Special", "Yanhe Tujia", "Yinjiang Tujia and Miao", "Yuping Dong"]);
		this.add("0_7_8", ["Chishui", "Daozhen Gelao and Miao", "Fenggang", "Meitan", "Renhuai", "Suiyang", "Tongzi", "Wuchuan Gelao and Miao", "Xishui", "Yuqing", "Zheng'an", "Zunyi Sh\u00e7\u0178", "Zunyi Xi\u00e8\u201e\u00bfn"]);
		this.add("0_8_0", ["Haikou", "Qiongshan"]);
		this.add("0_8_1", ["Baisha Li", "Baoting Li", "Changjiang Li", "Chengmai", "Danzhou", "Ding An", "Dongfang", "Ledong Li", "Lingao", "Lingshui Li", "Qionghai", "Qiongzhong Li and Miao", "Tunchang", "Wanning", "Wenchang"]);
		this.add("0_8_2", ["Sanya"]);
		this.add("0_9_0", ["Anguo", "Anxin", "Baoding", "Boye", "Ding", "Dingxing", "Fuping", "Gaoyang", "Laishui", "Laiyuan", "Li", "Mancheng", "Qing Yuan", "Quyang", "Rongcheng", "Tang", "Wan", "Wangdu", "Xincheng", "Xiong", "Xushui", "Yi", "Zhuo"]);
		this.add("0_9_1", ["Cang", "Cangzhou", "Dongguang", "Haixing", "Hejian", "Huanghua", "Jiaohe", "Mengcun Hui", "Nanpi", "Qing", "Renqiu", "Suning", "Wuqiao", "Xian", "Yanshan"]);
		this.add("0_9_2", ["Chengde Sh\u00e7\u0178", "Chengde Xi\u00e8\u201e\u00bfn", "Fengning Manchu", "Kuancheng Manchu", "Longhua", "Luanping", "Pingquan", "Weichang Manchu and Mongol", "Xinglong", "Yingshouyingzikuang"]);
		this.add("0_9_3", ["Cheng'an", "Ci", "Daming", "Feixiang", "Fengfengkuang", "Guangping", "Guantao", "Handan Xi\u00e8\u201e\u00bfn", "Handan sh\u00e7\u0178", "Jize", "Linzhang", "Qiu", "Quzhou", "She", "Wei", "Wu'an", "Yongnian"]);
		this.add("0_9_4", ["Anping", "Fucheng", "Gucheng", "Hengshui", "Ji", "Jing", "Raoyang", "Shen", "Wuqiang", "Wuyi", "Zaoqiang"]);
		this.add("0_9_5", ["Ba", "Dachang Hui", "Daicheng", "Gu'an", "Longfang", "Sanhe", "Wen'an", "Xianghe", "Yongqing"]);
		this.add("0_9_6", ["Changli", "Funing", "Lulong", "Qinglong", "Qinhuangdao"]);
		this.add("0_9_7", ["Gaocheng", "Gaoyi", "Huelu", "Ji", "Jingjing", "Lingshou", "Luancheng", "Pingshan", "Shenze", "Shijiazhuang", "Shulu", "Wuji", "Xingtang", "Xinle", "Yuanshi", "Zanhuang", "Zhao", "Zhengding"]);
		this.add("0_9_8", ["Fengnan", "Fengrun", "Leting", "Luan", "Luannan", "Qian'an", "Qianxi", "Tanghai", "Tangshan", "Yutian", "Zunhua"]);
		this.add("0_9_9", ["Baixiang", "Guangzong", "Julu", "Lincheng", "Linxi", "Longyao", "Nangong", "Nanhe", "Neiqiu", "Ningjin", "Pingxiang", "Qinghe", "Ren", "Shahe", "Wei", "Xingtai Xi\u00e8\u201e\u00bfn", "Xingtai sh\u00e7\u0178", "Xinhe"]);
		this.add("0_9_10", ["Chicheng", "Chongli", "Guyuan", "Huai'an", "Huailai", "Kangbao", "Shangyi", "Wanquan", "Xuanhua", "Yangyuan", "Yu", "Zhangbei", "Zhangjiakou", "Zhuolu"]);
		this.add("0_10_0", ["Daqina", "Dorbod Mongol", "Lindian", "Zhaoyuan", "Zhaozhou"]);
		this.add("0_10_1", ["Huma", "Huzhong", "Mohe", "Tahe", "Xinlin"]);
		this.add("0_10_2", ["Acheng", "Bayan", "Bin", "Fangzheng", "Harbin", "Hulan", "Mulan", "Shangzhi", "Shuangcheng", "Tonghe", "Wuchang", "Yanshou", "Yilan"]);
		this.add("0_10_3", ["Hegang", "Hegang sh\u00e7\u0178", "Luobei", "Suibin"]);
		this.add("0_10_4", ["Bei'an", "Dedu", "Heihe", "Nenjiang", "Sunwu", "Wudalianchi", "Xunke"]);
		this.add("0_10_5", ["Fujin", "Fuyuan", "Huachuan", "Huanan", "Jiamusi", "Tangyuan", "Tongjiang"]);
		this.add("0_10_6", ["Hulin", "Jidong", "Jixi", "Mishan"]);
		this.add("0_10_7", ["Dongning", "Hailin", "Linkou", "Mudanjiang", "Muling", "Ning'an", "Suifenhe"]);
		this.add("0_10_8", ["Baiquan", "Fuyu", "Gannan", "Kedong", "Keshan", "Longjiang", "Nehe", "Nianzishan", "Qiqihar", "Tailai", "Yi'an"]);
		this.add("0_10_9", ["Boli", "Qitaihe"]);
		this.add("0_10_10", ["Baoqing", "Jixian", "Raohe", "Shuangyashan", "Youyi"]);
		this.add("0_10_11", ["Anda", "Hailun", "Lanxi", "Mingshui", "Qing'an", "Qinggang", "Suihua", "Suileng", "Wangkui", "Zhaodong"]);
		this.add("0_10_12", ["Cuiluan", "Fengcheng", "Fengxin", "Gao'an", "Jiayin", "Jing'an", "Shanggao", "Tieli", "Tonggu", "Wanzai", "Wuyiling", "Yichun", "Yifeng", "Zhangshu"]);
		this.add("0_11_0", ["Anyang Sh\u00e7\u0178", "Anyang Xi\u00e8\u201e\u00bfn", "Hua", "Lin", "Neihuang", "Tangyin"]);
		this.add("0_11_1", ["Hebi", "Qi", "Xun"]);
		this.add("0_11_2", ["Bo'ai", "Jiaozuo", "Meng", "Qinyang", "Wen", "Wuzhi", "Xiuwu"]);
		this.add("0_11_3", ["Jiyuan"]);
		this.add("0_11_4", ["Kaifeng", "Kaifeng Xi\u00e8\u201e\u00bfn", "Lankao", "Qi", "Tongxu", "Weishi"]);
		this.add("0_11_5", ["Linying", "Luohe", "Wuyang", "Yancheng"]);
		this.add("0_11_6", ["Luanchuan", "Luoning", "Luoyang", "Mengjin", "Ruyang", "Song", "Xin'an", "Yanshi", "Yichuan", "Yiyang"]);
		this.add("0_11_7", ["Deng", "Fangcheng", "Nanyang Sh\u00e7\u0178", "Nanyang Xi\u00e8\u201e\u00bfn", "Nanzhao", "Neixiang", "Sheqi", "Tanghe", "Tongbai", "Xichuan", "Xinye", "Xixia", "Zhenping"]);
		this.add("0_11_8", ["Baofeng", "Jia", "Linru", "Lushan", "Pingdingshan", "Wugang", "Ye"]);
		this.add("0_11_9", ["Fanxian", "Nanle", "Puyang Sh\u00e7\u0178", "Puyang Xi\u00e8\u201e\u00bfn", "Qingfeng", "Taiqian"]);
		this.add("0_11_10", ["Lingbao", "Lushi", "Mianchi", "Sanmenxia", "Shan", "Yima"]);
		this.add("0_11_11", ["Minquan", "Ningling", "Shangqiu Sh\u00e7\u0178", "Sui", "Suiyang", "Xiayi", "Yongcheng", "Yucheng", "Zhecheng"]);
		this.add("0_11_12", ["Changyuan", "Fengqiu", "Houjia", "Huixian", "Ji", "Xinxiang Sh\u00e7\u0178", "Xinxiang Xi\u00e8\u201e\u00bfn", "Yanjin", "Yuanyang"]);
		this.add("0_11_13", ["Guangshan", "Gushi", "Huaibin", "Huangchuan", "Luoshan", "Shancheng", "Xi", "Xinxian", "Xinyang Sh\u00e7\u0178", "Xinyang Xi\u00e8\u201e\u00bfn"]);
		this.add("0_11_14", ["Changge", "Xiangcheng", "Xuchang Sh\u00e7\u0178", "Xuchang Xi\u00e8\u201e\u00bfn", "Yanling", "Yu"]);
		this.add("0_11_15", ["Dengfeng", "Gong", "Mi", "Xingyang", "Xinzheng", "Zhengzhou", "Zhongmou"]);
		this.add("0_11_16", ["Dancheng", "Fugou", "Huaiyang", "Luyi", "Shangshui", "Shenqiu", "Taikang", "Xiangcheng", "Xihua", "Zhoukou"]);
		this.add("0_11_17", ["Biyang", "Pingyu", "Queshan", "Runan", "Shangcai", "Suiping", "Xincai", "Xiping", "Zhengyang", "Zhumadian"]);
		this.add("0_12_0", ["Badong", "Enshi Tujia and Miao", "Hefeng", "Jianshi", "Laifeng", "Lichuan", "Xianfeng", "Xuan En"]);
		this.add("0_12_1", ["Echeng Q\u00e5\u00a5", "Echeng Sh\u00e7\u0178"]);
		this.add("0_12_2", ["Guangji", "Hong'an", "Huanggang", "Huangmei", "Luotian", "Macheng", "Qichun", "Xishui", "Yingshan"]);
		this.add("0_12_3", ["Daye", "Huangshi", "Yangxin"]);
		this.add("0_12_4", ["Jingmen", "Jingshan", "Shayang", "Zhongxiang"]);
		this.add("0_12_5", ["Gong'an", "Honghu", "Jiangling", "Jianli", "Jingzhou", "Shashi", "Shishou", "Songzi"]);
		this.add("0_12_6", ["Qianjiang"]);
		this.add("0_12_7", ["Shennongjia"]);
		this.add("0_12_8", ["Fang", "Junxian", "Shiyan", "Yun", "Yunxi", "Zhushan", "Zhuxi"]);
		this.add("0_12_9", ["Suizhou", "Yingshan"]);
		this.add("0_12_10", ["Tianmen"]);
		this.add("0_12_11", ["Hanyang", "Huangpi", "Wuchang", "Wuhan", "Xinzhou"]);
		this.add("0_12_12", ["Baokang", "Gucheng", "Laohekou", "Nanzhang", "Xiangfan", "Xiangyang", "Yicheng", "Zaoyang"]);
		this.add("0_12_13", ["Chongyang", "Jiayu", "Puqi", "Tongcheng", "Tongshan", "Xianning"]);
		this.add("0_12_14", ["Mianyang"]);
		this.add("0_12_15", ["Anlu", "Dawu", "Hanchuan", "Xiaochang", "Xiaogan", "Yingcheng", "Yunmeng"]);
		this.add("0_12_16", ["Changyang Tujia", "Dangyang", "Wufeng Tujia", "Xingshan", "Yichang", "Yidu", "Yiling", "Yuan'an", "Zhijiang", "Zigui"]);
		this.add("0_13_0", ["Anxiang", "Dingcheng", "Hanshou", "Jinshi", "Li", "Linli", "Shimen", "Taoyuan", "Wuling"]);
		this.add("0_13_1", ["Changsha Sh\u00e7\u0178", "Changsha Xi\u00e8\u201e\u00bfn", "Liuyang", "Ningxiang", "Wangcheng"]);
		this.add("0_13_2", ["Anren", "Chen", "Chenzhou", "Guidong", "Guiyang", "Jiahe", "Linwu", "Rucheng", "Yizhang", "Yongxing", "Zixing"]);
		this.add("0_13_3", ["Changning", "Hengdong", "Hengnan", "Hengshan", "Hengyang Sh\u00e7\u0178", "Hengyang Xi\u00e8\u201e\u00bfn", "Laiyang", "Qidong"]);
		this.add("0_13_4", ["Chenxi", "Huaihua", "Huitong", "H\u00e8\u00b4\u00b8ngji\u00e8\u2020\u00a9ng Q\u00e5\u00a5", "H\u00e8\u00b4\u00b8ngji\u00e8\u2020\u00a9ng Sh\u00e7\u0178", "Jing", "Mayang Miao", "Tongdao Dong", "Xinhuang Dong Dongzu", "Xupu", "Yuanling", "Zhijiang Dong Dongzu"]);
		this.add("0_13_5", ["Lengshuijang", "Lianyuan", "Loudi", "Shuangfeng", "Xinhua"]);
		this.add("0_13_6", ["Chengbu Miao", "Daxiang", "Dongkou", "Longhui", "Shaodong", "Shaoyang Sh\u00e7\u0178", "Shaoyang Xi\u00e8\u201e\u00bfn", "Suining", "Wugang", "Xinning", "Xinshao"]);
		this.add("0_13_7", ["Shaoshan", "Xiangtan Sh\u00e7\u0178", "Xiangtan Xi\u00e8\u201e\u00bfn", "Xiangxiang"]);
		this.add("0_13_8", ["Baojing", "Fenghuang", "Guzhang", "Huayuan", "Jishou", "Longshan", "Luxi", "Yongshun"]);
		this.add("0_13_9", ["Anhua", "Nan", "Taojiang", "Yiyang Sh\u00e7\u0178", "Yiyang Xi\u00e8\u201e\u00bfn", "Yuanjiang"]);
		this.add("0_13_10", ["Dao", "Jianghua Yao", "Jiangyong", "Lanshan", "Lengshuitan", "Lingling", "Ningyuan", "Qiyang", "Shuangpai", "Xintian"]);
		this.add("0_13_11", ["Huarong", "Linxiang", "Miluo", "Pingjiang", "Xiangyin", "Yueyang Q\u00e5\u00a5", "Yueyang Xi\u00e8\u201e\u00bfn"]);
		this.add("0_13_12", ["Cili", "Dayong", "Sangzhi"]);
		this.add("0_13_13", ["Chaling", "Liling", "Ling", "Youxian", "Zhuzhou Q\u00e5\u00a5", "Zhuzhou Xi\u00e8\u201e\u00bfn"]);
		this.add("0_14_0", ["Changzhou", "Jintan", "Liyang", "Wujin"]);
		this.add("0_14_1", ["Hongze", "Huaian", "Huaiyin", "Jinhu", "Lianshui", "Qingjiang", "Xuyi"]);
		this.add("0_14_2", ["Donghai", "Ganyu", "Guannan", "Guanyun", "Lianyungang"]);
		this.add("0_14_3", ["Gaochun", "Jiangning", "Jiangpu", "Lishui", "Luhe", "Nanjing"]);
		this.add("0_14_4", ["Hai'an", "Haimen", "Nantong", "Qidong", "Rudong", "Rugao", "Tongzhou"]);
		this.add("0_14_5", ["Shuyang", "Sihong", "Siyang", "Suqian", "Suyu"]);
		this.add("0_14_6", ["Changshu", "Dangshan", "Kunshan", "Lingbi", "Shazhou", "Si", "Suzhou", "Taicang", "Wujiang", "Wuxian", "Xiao", "Yongqiao"]);
		this.add("0_14_7", ["Huangyan", "Jiangyan", "Jingjiang", "Linhai", "Sanmen", "Taixing", "Taizhou", "Tiantai", "Wenling", "Xianju", "Xinghua", "Yuhuan"]);
		this.add("0_14_8", ["Jiangyin", "Wuxi", "Wuxi New District", "Xishan", "Yixing"]);
		this.add("0_14_9", ["Feng", "Pei", "Pizhou", "Suining", "Tongshan", "Xinyi", "Xuzhou"]);
		this.add("0_14_10", ["Binhai", "Dafeng", "Dongtai", "Funing", "Jianhu", "Sheyang", "Xiangshui", "Yandu", "Yiancheng"]);
		this.add("0_14_11", ["Baoying", "Gaoyou", "Hanjiang", "Jiangdu", "Yangzhou", "Yizheng"]);
		this.add("0_14_12", ["Dantu", "Danyang", "Jurong", "Yangzhong", "Zhenjiang"]);
		this.add("0_15_0", ["Changle", "Chongren", "Dongxiang", "Fuqing", "Fuzhou", "Guangchang", "Jinxi", "Le'an", "Lianjiang", "Lichuan", "Linchuan", "Luoyuan", "Minhou", "Minqing", "Nancheng", "Nanfeng", "Yihuang", "Yongtai", "Zixi"]);
		this.add("0_15_1", ["Anyuan", "Chongyi", "Dayu", "Dingnan", "Gan", "Ganzhou", "Huichang", "Longnan", "Nankang", "Ningdu", "Quannan", "Ruijin", "Shangyou", "Shicheng", "Xinfeng", "Xingguo", "Xunwu", "Yudu"]);
		this.add("0_15_2", ["Anfu", "Ji An", "Ji'an", "Jinggangshan", "Jishui", "Ninggang", "Suichuan", "Taihe", "Wan\u00e9\u02c6\u00a5\u00e6\u00aa\u0192n", "Xiajiang", "Xingan", "Yongfeng", "Yongxin"]);
		this.add("0_15_3", ["Jingdezhen", "Leping"]);
		this.add("0_15_4", ["De'an", "Duchang", "Hukou", "Jiujiang Q\u00e5\u00a5", "Jiujiang Xi\u00e8\u201e\u00bfn", "Pengze", "Ruichang", "Wuning", "Xingzi", "Xiushui", "Yongxiu"]);
		this.add("0_15_5", ["Anyi", "Jinxian", "Nanchang Q\u00e5\u00a5", "Nanchang Xi\u00e8\u201e\u00bfn", "Xingan", "Xinjian"]);
		this.add("0_15_6", ["Lianhua", "Pingxiang"]);
		this.add("0_15_7", ["Boyang", "Dexing", "Guangfeng", "Hengfeng", "Qianshan", "Shangrao Sh\u00e7\u0178", "Shangrao Xi\u00e8\u201e\u00bfn", "Wannian", "Wuyuan", "Yiyang", "Yugan", "Yushan"]);
		this.add("0_15_8", ["Fenyi", "Xinyu"]);
		this.add("0_15_9", ["Cuiluan", "Fengcheng", "Fengxin", "Gao'an", "Jiayin", "Jing'an", "Shanggao", "Tieli", "Tonggu", "Wanzai", "Wuyiling", "Yichun", "Yifeng", "Zhangshu"]);
		this.add("0_15_10", ["Guixi", "Yingtan", "Yujiang"]);
		this.add("0_16_0", ["Baicheng", "Da'an", "Taonan", "Tongyu", "Zhenlai"]);
		this.add("0_16_1", ["Badaojiang", "Changbai Korean", "Fusong", "Jiangyuan", "Jingyu", "Linjiang"]);
		this.add("0_16_2", ["Changchun", "Dehui", "Jiutai", "Nong'an", "Shuangyang", "Yushu"]);
		this.add("0_16_3", ["Huadian", "Jiaohe", "Jilin", "Panshi", "Shulan", "Yongji"]);
		this.add("0_16_4", ["Dongfeng", "Dongliao", "Liaoyuan"]);
		this.add("0_16_5", ["Huaide", "Lishu", "Shuangliao", "Siping", "Yitong Manchu"]);
		this.add("0_16_6", ["Changling", "Fuyu", "Qian Gorlos Mongol", "Qian'an"]);
		this.add("0_16_7", ["Dongchang", "Erdaojiang", "Huinan", "Ji'an", "Liuhe", "Meihekou", "Tonghua"]);
		this.add("0_16_8", ["Antu", "Dunhua", "Helong", "Hunchun", "Longjing", "Tumen", "Wangqing", "Yanji"]);
		this.add("0_17_0", ["Kaohsiung City"]);
		this.add("0_18_0", ["Anshan", "Haicheng", "Tai'an", "Xiuyan Manchu"]);
		this.add("0_18_1", ["Benxi", "Benxi Manchu", "Huanren Manchu"]);
		this.add("0_18_2", ["Beipiao", "Chaoyang Sh\u00e7\u0178", "Chaoyang Xi\u00e8\u201e\u00bfn", "Harqin Left Mongol", "Jianping", "Lingyuan"]);
		this.add("0_18_3", ["Changhai", "Dalian", "Jinzhou", "Lushunkou", "Wafangdian", "Xinjin", "Zhuanghe"]);
		this.add("0_18_4", ["Dadong", "Donggang", "Fengcheng", "Kuandian Manchu"]);
		this.add("0_18_5", ["Fushun", "Qingyuan Manchu", "Shuncheng", "Xinbin Manchu"]);
		this.add("0_18_6", ["Fuxin", "Fuxin Mongol", "Zhangwu"]);
		this.add("0_18_7", ["Jianchang", "Jinxi", "Suizhong", "Xingcheng"]);
		this.add("0_18_8", ["Beizhen", "Heishan", "Jin", "Jinzhou", "Yi"]);
		this.add("0_18_9", ["Dengta", "Liaoyang"]);
		this.add("0_18_10", ["Dawa", "Panjin", "Panshan"]);
		this.add("0_18_11", ["Faku", "Kangping", "Liaozhong", "Shenyang Sh\u00e7\u0178", "Shenyang Xi\u00e8\u201e\u00bfn", "Xinmin"]);
		this.add("0_18_12", ["Changtu", "Gai", "Kaiyuan", "Tiefa", "Tieling Sh\u00e7\u0178", "Tieling Xi\u00e8\u201e\u00bfn", "Xifeng", "Yingkou", "Yinzhou"]);
		this.add("0_19_0", ["Alxa Left", "Alxa Right", "Ejin"]);
		this.add("0_19_1", ["Baotou", "Darhan Muminggan Lia", "Guyang"]);
		this.add("0_19_2", ["Dengkou", "Haibowan", "Linhe", "Urad Back", "Urad Front", "Urad Middle", "Wuyuan"]);
		this.add("0_19_3", ["Aohan", "Ar Horqin", "Bairin Left", "Bairin Right", "Chifeng", "Harqin", "Hexigten", "Linxi", "Ningcheng", "Ongniud"]);
		this.add("0_19_4", ["Hohhot", "Horinger", "Qingshuihe", "Togtoh", "Tumd Left", "Tumd Right", "Wuchuan"]);
		this.add("0_19_5", ["Arun", "Butha Qi", "Chenbarag Qi", "Ergun", "Evenk", "Genhe", "Hailar", "Manzhouli", "Morin Dawa Daur", "Oroqin", "Xinbarag Left", "Xinbarag Right", "Xuguit Qi"]);
		this.add("0_19_6", ["Dalad", "Dongsheng", "Ejin Horo", "Hanggin", "Jungar", "Otog", "Otog Front", "Uxin"]);
		this.add("0_19_7", ["Horqin Left Back", "Horqin Left Middle", "Huolin Gol", "Hure", "Jarud", "Kailu", "Naiman", "Tongliao"]);
		this.add("0_19_8", ["Fengzhen", "Huade", "Jining", "Liangcheng", "Qahar Youyi Houqi", "Qahar Youyi Qianqi", "Qahar Youyi Zhongqi", "Shangdu", "Siziwang", "Xinghe", "Zhuozi"]);
		this.add("0_19_9", ["Wuhai"]);
		this.add("0_19_10", ["Abag", "Abagnar Qi", "Bordered Yellow", "Dong Ujimqin", "Duolun", "Erenhot", "Plain Blue", "Plain and Bordered White", "Sonid Left", "Sonid Right", "Taibus", "West Ujimqin"]);
		this.add("0_19_11", ["Horqin Right Front", "Horqin Right Middle", "Jalaid", "Tuquan", "Ulan Hot"]);
		this.add("0_20_0", ["Guyuan", "Jingyuan", "Longde", "Pengyang", "Xiji"]);
		this.add("0_20_1", ["Huinong", "Pingluo", "Shizuishan Q\u00e5\u00a5", "Shizuishan Sh\u00e7\u0178", "Taole"]);
		this.add("0_20_2", ["Qingtongxia", "Tongxin", "Wuzhong", "Yanchi"]);
		this.add("0_20_3", ["Helan", "Lingwu", "Yinchuan", "Yongning"]);
		this.add("0_20_4", ["Haiyuan", "Zhongning", "Zhongwei"]);
		this.add("0_21_0", ["Pratas Islands"]);
		this.add("0_22_0", ["Baima", "Darlag", "Gad\u00e9\u201d", "Jigzhi", "Madoi", "Maq\u00e9\u201d\u0161n"]);
		this.add("0_22_1", ["Chindu", "Golmud", "Nangq\u00e9\u201d\u0161n", "Qumarleb", "Yushu", "Zadoi", "Zhidoi"]);
		this.add("0_22_2", ["Gangca", "Haiyan", "Menyuan Hui", "Qilian"]);
		this.add("0_22_3", ["Hualong Hui", "Huzhu Tu", "Ledu", "Minhe Hui and Tu", "Ping'an", "Xunhua Salar"]);
		this.add("0_22_4", ["Gonghe", "Guide", "Guinan", "Tongde", "Xinghai"]);
		this.add("0_22_5", ["Delingha", "Dulan", "Golmud", "Lenghu", "Tianjun", "Wulan"]);
		this.add("0_22_6", ["Henan Mongol", "Jainca", "Tongren", "Z\u00e9\u201d\u0161kog"]);
		this.add("0_22_7", ["Datong Hui and Tu", "Huangyuan", "Huangzhong", "Xining"]);
		this.add("0_23_0", ["Ankang", "Baihe", "Hanyin", "Langao", "Ningshan", "Pingli", "Shiquan", "Xunyang", "Zhenping", "Ziyang"]);
		this.add("0_23_1", ["Baoji Q\u00e5\u00a5", "Baoji Xi\u00e8\u201e\u00bfn", "Feng", "Fengxiang", "Fufeng", "Linyou", "Long", "Mei", "Qianyang", "Qishan", "Taibai"]);
		this.add("0_23_2", ["Chenggu", "Foping", "Hanzhong", "Liuba", "Lueyang", "Mian", "Nanzheng", "Ningqiang", "Xixiang", "Yang", "Zhenba"]);
		this.add("0_23_3", ["Danfeng", "Luonan", "Shang", "Shangnan", "Shanyang", "Zhashui", "Zhen'an"]);
		this.add("0_23_4", ["Tongchuan", "Yijun"]);
		this.add("0_23_5", ["Baishui", "Chencang", "Dali", "Fuping", "Hancheng", "Heyang", "Hua", "Huayin", "Pucheng", "Tongguan", "Weinan"]);
		this.add("0_23_6", ["Chang'an", "Gaoling", "Hu", "Lantian", "Lintong", "Xincheng", "Zhouzhi"]);
		this.add("0_23_7", ["Bin", "Changwu", "Chunhua", "Jingyang", "Liquan", "Qian", "Sanyuan", "Wugong", "Xianyang", "Xingping", "Xunyi", "Yangling", "Yongshou"]);
		this.add("0_23_8", ["Ansai", "Fu", "Ganquan", "Huangling", "Huanglong", "Luochuan", "Wuqi", "Yan An", "Yanchang", "Yanchuan", "Yichuan", "Zhidan", "Zichang"]);
		this.add("0_23_9", ["Beiliu", "Bobai", "Dingbian", "Fugu", "Hengshan", "Jia", "Jingbian", "Luchuan", "Mizhi", "Qingjian", "Rong", "Shenmu", "Suide", "Wubu", "Yufeng", "Yulin", "Zizhou"]);
		this.add("0_24_0", ["Binxian", "Boxing", "Huimin", "Wudi", "Yangxin", "Zhanhua", "Zouping"]);
		this.add("0_24_1", ["Dezhou", "Leling", "Ling", "Linyi", "Ningjin", "Pingyuan", "Qihe", "Qingyun", "Wucheng", "Xiajin", "Yuncheng"]);
		this.add("0_24_2", ["Dongying", "Guangrao", "Hekou", "Kenli", "Lijin"]);
		this.add("0_24_3", ["Cao", "Chengwu", "Dingtao", "Dongming", "Heze", "Juancheng", "Juye", "Shan", "Yucheng"]);
		this.add("0_24_4", ["Changqing", "Jinan", "Jiyang", "Pingyin", "Shanghe", "Zhangqiu"]);
		this.add("0_24_5", ["Jiaxiang", "Jining", "Jinxiang", "Liangshan", "Qufu", "Sishui", "Weishan", "Wenshang", "Yanzhou", "Yutai"]);
		this.add("0_24_6", ["Laiwu"]);
		this.add("0_24_7", ["Chiping", "Dong'e", "Gaotang", "Guan", "Liaocheng", "Linqing", "Shenxian", "Yanggu"]);
		this.add("0_24_8", ["Cangshan", "Feixian", "Junan", "Linshu", "Linyi", "Mengyin", "Pingyi", "Tancheng", "Yinan", "Yishui"]);
		this.add("0_24_9", ["Huangdao", "Jiaonan", "Jiaoxian", "Jimo", "Laixi", "Laoshan", "Pingdu"]);
		this.add("0_24_10", ["Juxian", "Rizhao", "Wulian"]);
		this.add("0_24_11", ["Dongping", "Feicheng", "Ningyang", "Tai An", "Xinwen"]);
		this.add("0_24_12", ["Anqiu", "Changle", "Changyi", "Gaomi", "Linqu", "Qingzhou", "Shouguang", "Weifang Sh\u00e7\u0178", "Weifang Xi\u00e8\u201e\u00bfn", "Zhucheng"]);
		this.add("0_24_13", ["Rencheng", "Rushan", "Weihai", "Wendeng"]);
		this.add("0_24_14", ["Changdao", "Fushan", "Haiyang", "Laiyang", "Laizhou", "Longkou", "Muping", "Penglai", "Qixia", "Yantai", "Zhaoyuan"]);
		this.add("0_24_15", ["Teng", "Zhaozhuang", "Zouxian"]);
		this.add("0_24_16", ["Gaoqing", "Huantai", "Yiyuan", "Zibo", "Zichuan"]);
		this.add("0_25_0", ["Baoshan", "Chongming", "Fengxian", "Jiading", "Jinshan", "Minhang", "Nanhui", "Pudong", "Qingpu", "Shanghai", "Shengsi", "Songjiang"]);
		this.add("0_26_0", ["Changzhi Sh\u00e7\u0178", "Changzhi Xi\u00e8\u201e\u00bfn", "Huguan", "Licheng", "Lucheng", "Pingshun", "Qin", "Qinyuan", "Tunliu", "Wuxiang", "Xiangyuan", "Zhangzi"]);
		this.add("0_26_1", ["Datong Sh\u00e7\u0178", "Datong Xi\u00e8\u201e\u00bfn", "Guangling", "Hunyuan", "Lingqiu", "Tianzhen", "Yanggao", "Zuoyun"]);
		this.add("0_26_2", ["Gaoping", "Jingcheng", "Lingchuan", "Qinshui", "Yangcheng"]);
		this.add("0_26_3", ["Heshun", "Jiexiu", "Lingshi", "Pingyao", "Qi", "Shouyang", "Taigu", "Xiyang", "Yuci", "Yushe", "Zuoquan"]);
		this.add("0_26_4", ["Anze", "Daning", "Fenxi", "Fushan", "Gu", "Hongtong", "Houma", "Huo", "Ji", "Linfen", "Pu", "Quwo", "Xi", "Xiangfen", "Xiangning", "Yicheng", "Yonghe"]);
		this.add("0_26_5", ["Fangshan", "Fenyang", "Jiaocheng", "Jiaokou", "Lan", "Lin", "Lishi", "Liulin", "Shilou", "Wenshui", "Xiaoyi", "Xing", "Zhongyang"]);
		this.add("0_26_6", ["Huairen", "Pinglu", "Shanyin", "Shuo", "Ying", "Youyu"]);
		this.add("0_26_7", ["Gujiao", "Loufan", "Qingxu", "Taiyuan", "Yangqu"]);
		this.add("0_26_8", ["Baode", "Dai", "Dingxiang", "Fanshi", "Hequ", "Jingle", "Kelan", "Ningwu", "Pianguan", "Shenchi", "Wutai", "Wuzhai", "Xinfu", "Yuanping"]);
		this.add("0_26_9", ["Pingding", "Yangquan", "Yu"]);
		this.add("0_26_10", ["Hejin", "Jiang", "Jishan", "Linyi", "Pinglu", "Ruicheng", "Wanrong", "Wenxi", "Xia", "Xinjiang", "Yongji", "Yuanqu", "Yuncheng"]);
		this.add("0_27_0", ["Bazhong", "Nanjiang", "Pingchang", "Tongjiang"]);
		this.add("0_27_1", ["Chengdu Q\u00e5\u00a5", "Chengdu Sh\u00e7\u0178", "Chongqing", "Dayi", "Jintang", "Peng", "Pi", "Pujiang", "Qionglai", "Shuangliu", "Wenjiang", "Xindu", "Xinjin"]);
		this.add("0_27_2", ["Da", "Daxian", "Dazhu", "Kaijiang", "Qu", "Wanyuan", "Xuanhan"]);
		this.add("0_27_3", ["Deyang", "Guanghan", "Mianzhu", "Shifang", "Zhongjiang"]);
		this.add("0_27_4", ["Baiy\u00e7\u0153", "Batang", "Danba", "Daocheng", "Dawu", "D\u00e9\u201d\u0161g\u00e9\u201d", "D\u00e9\u201d\u0161rong", "Garz\u00e9\u201d", "Jiulong", "Kangding", "Litang", "Luding", "Luhuo", "S\u00e9\u201d\u0161rtar", "S\u00e9\u201d\u0161rx\u00e7\u0153", "Xiangcheng", "Xinlong", "Yajiang"]);
		this.add("0_27_5", ["Guang'an", "Huayun", "Linshui", "Wusheng", "Yuechi"]);
		this.add("0_27_6", ["Cangxi", "Chaotian", "Jiange", "Qingchuan", "Shizhong", "Wangcang", "Yuanba"]);
		this.add("0_27_7", ["Ebian Yi", "Emeishan", "Jiajiang", "Jinkouhe", "Mabian Yi", "Muchuan", "Qianwei", "Shawan", "Shizhong", "Wutongqiao"]);
		this.add("0_27_8", ["Butuo", "Dechang", "Ganluo", "Huidong", "Huili", "Jingyang", "Leibo", "Meigu", "Mianning", "Muli Tibetan", "Ningnan", "Puge", "Xichang", "Xide", "Yanyuan", "Yuexi", "Zhaojue"]);
		this.add("0_27_9", ["Gulin", "Hejiang", "Lu", "Luzhou", "N\u00e8\u201e\u00bfx\u00e5\u00a2", "Xuyong"]);
		this.add("0_27_10", ["Danleng", "Hongya", "Jingyan", "Meishan", "Pengshan", "Qingshen", "Renshou"]);
		this.add("0_27_11", ["An", "Beichuan Qiang", "Jiangyou", "Mianyang", "Pingwu", "Santai", "Yanting", "Zitong"]);
		this.add("0_27_12", ["Langzhong", "Nanbu", "Nanchong Sh\u00e7\u0178", "Nanchong Xi\u00e8\u201e\u00bfn", "Peng'an", "Xichong", "Yilong", "Yingshan"]);
		this.add("0_27_13", ["Dongxing", "Shizhong", "Weiyuan"]);
		this.add("0_27_14", ["Longchang", "Zizhong"]);
		this.add("0_27_15", ["Aba", "Barkam", "Guan", "Heishui", "Hongyuan", "Jinchuan", "Li", "Mao", "Nanping", "Songpan", "Wenchuan", "Xiaojin", "Zamtang", "Zoig\u00e9\u201d"]);
		this.add("0_27_16", ["East", "Miyi", "Yanbian"]);
		this.add("0_27_17", ["Pengxi", "Shehong", "Suining"]);
		this.add("0_27_18", ["Baoxing", "Hanyuan", "Lushan", "Mingshan", "Shimian", "Tianquan", "Ya An", "Yingjing"]);
		this.add("0_27_19", ["Changning", "Gao", "Gong", "Jiang'an", "Junlian", "Nanxi", "Pingshan", "Xingwen", "Yibin Sh\u00e7\u0178", "Yibin Xi\u00e8\u201e\u00bfn"]);
		this.add("0_27_20", ["Fushun", "Rong", "Zigong"]);
		this.add("0_27_21", ["Anju", "Jiangyang", "Lezhi", "Ziyang"]);
		this.add("0_28_0", ["Changhwa"]);
		this.add("0_28_1", ["Chiayi"]);
		this.add("0_28_2", ["Hsinchu"]);
		this.add("0_28_3", ["Hualien"]);
		this.add("0_28_4", ["Ilan"]);
		this.add("0_28_5", ["Kaohsiung"]);
		this.add("0_28_6", ["Keelung City"]);
		this.add("0_28_7", ["Miaoli"]);
		this.add("0_28_8", ["Nantou"]);
		this.add("0_28_9", ["Penghu"]);
		this.add("0_28_10", ["Pingtung"]);
		this.add("0_28_11", ["Taichung"]);
		this.add("0_28_12", ["Taichung City"]);
		this.add("0_28_13", ["Tainan"]);
		this.add("0_28_14", ["Tainan City"]);
		this.add("0_28_15", ["Taipei", "Taipei City"]);
		this.add("0_28_16", ["Taitung"]);
		this.add("0_28_17", ["Taoyuan"]);
		this.add("0_28_18", ["Yunlin"]);
		this.add("0_29_0", ["Baodi", "Beichen", "Dagang", "Dongli", "Hangu", "Ji", "Jinghai", "Ninghe", "Tanggu", "Tianjin", "Wuqing", "Xiqing"]);
		this.add("0_30_0", ["Aksu", "Awat", "Baicheng", "Kalpin", "Kuqa", "Shayar", "Toksu", "Wensu", "Wushi"]);
		this.add("0_30_1", ["Altay", "Burqin", "Fuhai", "Fuyun", "Habahe", "Jeminay", "Qinggil"]);
		this.add("0_30_2", ["Bohu", "Hejing", "Hoxud", "Korla", "Luntai", "Qiemo", "Ruoqiang", "Yanqi Hui", "Yuli"]);
		this.add("0_30_3", ["Bole", "Jinghe", "Wenquan"]);
		this.add("0_30_4", ["Changji", "Fukang", "Hutubi", "Jimsar", "Manas", "Miquan", "Mori", "Qitai"]);
		this.add("0_30_5", ["Barkol Kazakh", "Hami", "Yiwu"]);
		this.add("0_30_6", ["Gongliu", "Huocheng", "Kuitun", "Nilka", "Qapqal Xibe", "Tekes", "Xinyuan", "Yining", "Yining Sh\u00e7\u0178", "Zhaosu"]);
		this.add("0_30_7", ["Dushanzi", "Karamay"]);
		this.add("0_30_8", ["Bachu", "Jiashi", "Kashgar", "Makit", "Poskam", "Shufu", "Shule", "Taxkorgan Tajik", "Yecheng", "Yengisar", "Yopurga", "Zepu"]);
		this.add("0_30_9", ["Khotan", "Lop", "Minfeng", "Moyu", "Pishan", "Qira", "Yutian"]);
		this.add("0_30_10", ["Akqi", "Akto", "Artux", "Wuqia"]);
		this.add("0_30_11", ["Shihezi"]);
		this.add("0_30_12", ["Emin", "Hoboksar Mongol", "Shawan", "Tacheng", "Toli", "Usu", "Yumin"]);
		this.add("0_30_13", ["Shanshan", "Toksun", "Turfan"]);
		this.add("0_30_14", ["\u00e8\u201e\u00bar\u00e7\u0153\u2030mqi Sh\u00e7\u0178", "\u00e8\u201e\u00bar\u00e7\u0153\u2030mqi Xi\u00e8\u201e\u00bfn"]);
		this.add("0_31_0", ["Banbar", "Baxoi", "D\u00e9\u201d\u0161ngq\u00e9\u201d\u0161n", "Gonjo", "Jomdo", "Lhorong", "Markam", "Qamdo", "Riwoq\u00e9\u201d", "Zhag'yab", "Zogang"]);
		this.add("0_31_1", ["Dagz\u00e9\u201d", "Damxung", "Doilungd\u00e9\u201d\u0161q\u00e9\u201d\u0161n", "Lhasa", "Lh\u00e7\u0153\u2030nzhub", "Maizhokunggar", "Ny\u00e9\u201d\u0161mo", "Q\u00e7\u0153\u2030x\u00e7\u0153"]);
		this.add("0_31_2", ["Amdo", "Baq\u00e9\u201d\u0161n", "Biru", "Lhari", "Nagchu", "Nyainrong", "Nyima", "Raingoin", "Sog", "Xainza"]);
		this.add("0_31_3", ["Burang", "Coq\u00e9\u201d\u0161n", "Gar", "G\u00e9\u201dgyai", "G\u00e9\u201d\u0161rz\u00e9\u201d", "Rutog", "Zanda"]);
		this.add("0_31_4", ["Bomi", "Gongbo'gyamda", "Mainling", "Nang", "Nyingchi", "Zay\u00e7\u0153"]);
		this.add("0_31_5", ["Comai", "Cona", "Gonggar", "Gyaca", "Lhozhag", "Lh\u00e7\u0153\u2030nz\u00e9\u201d", "Nagarz\u00e9\u201d", "N\u00e9\u201d\u0161dong", "Qonggyai", "Qusum", "Sangri", "Zhanang"]);
		this.add("0_31_6", ["Bainang", "Dinggy\u00e9\u201d", "Gamba", "Gyangz\u00e9\u201d", "Gyirong", "Kangmar", "Lhaz\u00e9\u201d", "Namling", "Ngamring", "Nyalam", "Rinbung", "Sa'gya", "Saga", "Shigatse", "Tingri", "Xaitongmoin", "Yadong", "Zhongba"]);
		this.add("0_32_0", ["Baoshan", "Changning", "Longling", "Shidian", "Tengchong"]);
		this.add("0_32_1", ["Chuxiong", "Dayao", "Lufeng", "Mouding", "Nanhua", "Shuangbai", "Wuding", "Yao'an", "Yongren", "Yuanmou"]);
		this.add("0_32_2", ["Binchuan", "Dali", "Eryuan", "Heqing", "Jianchuan", "Midu", "Nanjian Yi", "Weishan Yi and Hui", "Xiangyun", "Yangbi Yi", "Yongping", "Yulong Naxi"]);
		this.add("0_32_3", ["Lianghe", "Longchuan", "Luxi", "Ruili", "Yingjiang"]);
		this.add("0_32_4", ["D\u00e9\u201d\u0161q\u00e9\u201d\u0161n", "Weixin", "Zhongdian"]);
		this.add("0_32_5", ["Gejiu", "Hekou Yao", "Honghe", "Jianshui", "Jinping Miao, Yao and Dai", "Kaiyuan", "Luxi", "L\u00e7\u0153\u2030chun", "Mengzi", "Mile", "Pingbian Miao", "Shiping", "Yuanyang"]);
		this.add("0_32_6", ["Anning", "Chenggong", "Dongchuan", "Fumin", "Jinning", "Kunming", "Lunan", "Luquan Yi and Miao", "Songming", "Xishan", "Xundian Hui and Yi", "Yiliang"]);
		this.add("0_32_7", ["Huaping", "Lijiang", "Ninglang Yi", "Yongsheng"]);
		this.add("0_32_8", ["Cangyuan Va", "Fengqing", "Gengma Dai and Va", "Lincang", "Shuangjiang Lahu, Va, Blang and Dai", "Yongde", "Yun", "Zhenkang"]);
		this.add("0_32_9", ["Bijiang", "Gongshan Derung and Nu", "Lanping Bai and Pumi", "Lushui"]);
		this.add("0_32_10", ["Jiangcheng Hani and Yi", "Jingdong Yi", "Jinggu Dai and Yi", "Lancang Lahu", "Menglian Dai, Lahu and Va", "Mojiang Hani", "Puer", "Simao", "Ximeng Va", "Zhenyuan Yi, Hani and Lahu"]);
		this.add("0_32_11", ["Fuyuan", "Huize", "Luliang", "Luoping", "Malong", "Shizong", "Xuanwei", "Zhanyi"]);
		this.add("0_32_12", ["Funing", "Guangnan", "Maguan", "Malipo", "Qiubei", "Wenshan", "Xichou", "Yanshan"]);
		this.add("0_32_13", ["Jinghong", "Menghai", "Mengla"]);
		this.add("0_32_14", ["Chengjiang", "Eshan Yi", "Huaning", "Jiangchuan", "Tonghai", "Xinping Yi and Dai", "Yimen", "Yuanjiang Hani, Yi and Dai", "Yuxi"]);
		this.add("0_32_15", ["Daguan", "Ludian", "Qiaojia", "Shuifu", "Suijiang", "Weixi Lisu", "Yanjin", "Yiliang", "Yongshan", "Zhaotong", "Zhenxiong"]);
		this.add("0_33_0", ["Chun'an", "Fuyang", "Hangzhou", "Jiande", "Lin'an", "Tonglu", "Xiaoshan", "Yuhang"]);
		this.add("0_33_1", ["Anji", "Changxing", "Deqing", "Huzhou"]);
		this.add("0_33_2", ["Haining", "Haiyan", "Jiashan", "Jiaxing", "Pinghu", "Tongxiang", "Xiuzhou"]);
		this.add("0_33_3", ["Dongyang", "Jinhua Sh\u00e7\u0178", "Jinhua Xi\u00e8\u201e\u00bfn", "Lanxi", "Pan'an", "Pujiang", "Wuyi", "Yiwu", "Yongkang"]);
		this.add("0_33_4", ["Jingning She", "Jinyun", "Lishui", "Longquan", "Qingtian", "Qingyuan", "Songyang", "Suichang", "Yunhe"]);
		this.add("0_33_5", ["Cixi", "Fenghua", "Longwan", "Ninghai", "Xiangshan", "Xiuzhou", "Yuyao", "Zhenhai"]);
		this.add("0_33_6", ["Changshan", "Jiangshan", "Kaihua", "Longyou", "Quzhou Sh\u00e7\u0178", "Quzhou Xi\u00e8\u201e\u00bfn"]);
		this.add("0_33_7", ["Shangyu", "Shaoxing", "Shaoxing Xi\u00e8\u201e\u00bfn", "Shengsi", "Xinchang", "Zhuji"]);
		this.add("0_33_8", ["Huangyan", "Jiangyan", "Jingjiang", "Linhai", "Sanmen", "Taixing", "Taizhou", "Tiantai", "Wenling", "Xianju", "Xinghua", "Yuhuan"]);
		this.add("0_33_9", ["Cangnan", "Ouhai", "Pingyang", "Ruian", "Taishun", "Wencheng", "Wenzhou", "Yongjia", "Yueqing"]);
		this.add("0_33_10", ["Daishan", "Dinghai", "Putuo"]);
		this.add("0_0", ["Anqing", "Bengbu", "Bozhou", "Chaohu", "Chizhou", "Chuzhou", "Fuyang", "Hefei", "Huaibei", "Huainan", "Huangshan", "Lu'an", "Ma'anshan", "Suzhou", "Tongling", "Wuhu", "Xuancheng"]);
		this.add("0_1", ["Beijing"]);
		this.add("0_2", ["Chongqing"]);
		this.add("0_3", ["Fuzhou", "Longyan", "Nanping", "Ningde", "Putian", "Quanzhou", "Sanming", "Xiamen", "Zhangzhou"]);
		this.add("0_4", ["Baiyin", "Dingxi", "Gannan Tibetan", "Jiayuguan", "Jinchang", "Jiuquan", "Lanzhou", "Linxia Hui", "Longnan", "Pingliang", "Qingyang", "Tianshui", "Wuwei", "Zhangye"]);
		this.add("0_5", ["Chaozhou", "Dongguan", "Foshan", "Guangzhou", "Heyuan", "Huizhou", "Jiangmen", "Jieyang", "Maoming", "Meizhou", "Qingyuan", "Shantou", "Shanwei", "Shaoguan", "Shenzhen", "Yangjiang", "Yunfu", "Zhanjiang", "Zhaoqing", "Zhongshan", "Zhuhai"]);
		this.add("0_6", ["Baise", "Beihai", "Chongzuo", "Fangchenggang", "Guigang", "Guilin", "Hechi", "Hezhou", "Laibin", "Liuzhou", "Nanning", "Qinzhou", "Wuzhou", "Yulin"]);
		this.add("0_7", ["Anshun", "Bijie", "Guiyang", "Liupanshui", "Qiandongnan Miao and Dong", "Qiannan Buyei and Miao", "Qianxinan Buyei and Miao", "Tongren", "Zunyi"]);
		this.add("0_8", ["Haikou", "Hainan", "Sanya"]);
		this.add("0_9", ["Baoding", "Cangzhou", "Chengde", "Handan", "Hengshui", "Langfang", "Qinhuangdao", "Shijiazhuang", "Tangshan", "Xingtai", "Zhangjiakou"]);
		this.add("0_10", ["Daqing", "Daxing'anling", "Harbin", "Hegang", "Heihe", "Jiamusi", "Jixi", "Mudanjiang", "Qiqihar", "Qitaihe", "Shuangyashan", "Suihua", "Yichun"]);
		this.add("0_11", ["Anyang", "Hebi", "Jiaozuo", "Jiyuan shi", "Kaifeng", "Luohe", "Luoyang", "Nanyang", "Pingdingshan", "Puyang", "Sanmenxia", "Shangqiu", "Xinxiang", "Xinyang", "Xuchang", "Zhengzhou", "Zhoukou", "Zhumadian"]);
		this.add("0_12", ["Enshi Tujia and Miao", "Ezhou", "Huanggang", "Huangshi", "Jingmen", "Jingzhou", "Qianjiang", "Shennongjia", "Shiyan", "Suizhou Shi", "Tianmen", "Wuhan", "Xiangfan", "Xianning", "Xiantao", "Xiaogan", "Yichang"]);
		this.add("0_13", ["Changde", "Changsha", "Chenzhou", "Hengyang", "Huaihua", "Loudi", "Shaoyang", "Xiangtan", "Xiangxi Tujia and Miao", "Yiyang", "Yongzhou", "Yueyang", "Zhangjiajie", "Zhuzhou"]);
		this.add("0_14", ["Changzhou", "Huai'an", "Lianyungang", "Nanjing", "Nantong", "Suqian", "Suzhou", "Taizhou", "Wuxi", "Xuzhou", "Yancheng", "Yangzhou", "Zhenjiang"]);
		this.add("0_15", ["Fuzhou", "Ganzhou", "Ji'an", "Jingdezhen", "Jiujiang", "Nanchang", "Pingxiang", "Shangrao", "Xinyu", "Yichun", "Yingtan"]);
		this.add("0_16", ["Baicheng", "Baishan", "Changchun", "Jilin", "Liaoyuan", "Siping", "Songyuan", "Tonghua", "Yanbian Korean"]);
		this.add("0_17", ["Kaohsiung City"]);
		this.add("0_18", ["Anshan", "Benxi", "Chaoyang", "Dalian", "Dandong", "Fushun", "Fuxin", "Huludao", "Jinzhou", "Liaoyang", "Panjin", "Shenyang", "Tieling"]);
		this.add("0_19", ["Alxa", "Baotou", "Baynnur", "Chifeng", "Hohhot", "Hulunbuir", "Ordos", "Tongliao", "Ulaan Chab", "Wuhai", "Xilin Gol", "Xing'an"]);
		this.add("0_20", ["Guyuan", "Shizuishan", "Wuzhong", "Yinchuan", "Zhongwei"]);
		this.add("0_21", ["Pratas Islands"]);
		this.add("0_22", ["Golog Tibetan", "Gy\u00e9\u201d\u0161gu Tibetan", "Haibei Tibetan", "Haidong", "Hainan Tibetan", "Haixi Mongol and Tibetan", "Huangnan Tibetan", "Xining"]);
		this.add("0_23", ["Ankang", "Baoji", "Hanzhong", "Shangluo", "Tongchuan", "Weinan", "Xi'an", "Xianyang", "Yan'an", "Yulin"]);
		this.add("0_24", ["Binzhou", "Dezhou", "Dongying", "Heze", "Jinan", "Jining", "Laiwu", "Liaocheng", "Linyi", "Qingdao", "Rizhao", "Tai'an", "Weifang", "Weihai", "Yantai", "Zaozhuang", "Zibo"]);
		this.add("0_25", ["Shanghai"]);
		this.add("0_26", ["Changzhi", "Datong", "Jincheng", "Jinzhong", "Linfen", "Luliang", "Shuozhou", "Taiyuan", "Xinzhou", "Yangquan", "Yuncheng"]);
		this.add("0_27", ["Bazhong", "Chengdu", "Dazhou", "Deyang", "Garz\u00e9\u201dTibetan", "Guang'an", "Guangyuan", "Leshan", "Liangshan Yi", "Luzhou", "Meishan", "Mianyang", "Nanchong", "Neijiang", "Neijiang]);", "Ngawa Tibetan and Qiang", "Panzhihua", "Suining", "Ya'an", "Yibin", "Zigong", "Ziyang"]);
		this.add("0_28", ["Changhwa", "Chiayi", "Hsinchu", "Hualien", "Ilan", "Kaohsiung", "Keelung City", "Miaoli", "Nantou", "Penghu", "Pingtung", "Taichung", "Taichung City", "Tainan", "Tainan City", "Taipei", "Taitung", "Taoyuan", "Yunlin"]);
		this.add("0_29", ["Tianjin"]);
		this.add("0_30", ["Aksu", "Altay", "Bayin'gholin Mongol", "B\u00e6\u017e\u0161rtala Mongol", "Changji Hui", "Hami", "Ili Kazakh", "Karamay", "Kashgar", "Khotan", "Kizilsu Kirghiz", "Shihezi", "Tacheng", "Turfan", "\u00e8\u201e\u00bar\u00e7\u0153\u2030mqi"]);
		this.add("0_31", ["Chamdo", "Lhasa", "Nagchu", "Ngari", "Nyingtri", "Shannan", "Shigatse"]);
		this.add("0_32", ["Baoshan", "Chuxiong Yi", "Dali Bai", "Dehong Dai and Jingpo", "D\u00e9\u201d\u0161q\u00e9\u201d\u0161n Tibetan", "Honghe Hani and Yi", "Kunming", "Lijiang", "Lincang", "Nujiang Lisu", "Pu'er", "Qujing", "Wenshan Zhuang and Miao", "Xishuangbanna Dai", "Yuxi", "Zhaotong"]);
		this.add("0_33", ["Hangzhou", "Huzhou", "Jiaxing", "Jinhua", "Lishui", "Ningbo", "Quzhou", "Shaoxing", "Taizhou", "Wenzhou", "Zhoushan"]);
		this.add("0", ["Anhui", "Beijing", "Chongqing", "Fujian", "Gansu", "Guangdong", "Guangxi", "Guizhou", "Hainan", "Hebei", "Heilongjiang", "Henan", "Hubei", "Hunan", "Jiangsu", "Jiangxi", "Jilin", "Kaohsiung", "Liaoning", "Nei Mongol", "Ningxia Hui", "Pratas Islands", "Qinghai", "Shaanxi", "Shandong", "Shanghai", "Shanxi", "Sichuan", "Taiwan", "Tianjin", "Xinjiang Uygur", "Xizang", "Yunnan", "Zhejiang"]);
	

		for(var j=0;j<this.s.length-1;j++){
			document.getElementById(this.s[j]).onchange=new Function("pccs_change("+(j+1)+")");
		}
		pccs_change(0);
	}
};